services:

  postgres:
    image: postgres:16
    container_name: user-management-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: user_management
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - user-management-postgres-data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d user_management"]
      interval: 5s
      timeout: 5s
      retries: 10

    networks:
      - user-management-network

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: user-management-api
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_management
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    networks:
      - user-management-network

volumes:
  user-management-postgres-data:

networks:
  user-management-network:
    driver: bridge