spring:

  application:
    name: spring-user-management-api

  datasource:
    url: jdbc:postgresql://localhost:5432/user_management
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration


server:
  port: 8080


app:
  jwt:
    secret: change-this-secret-key-change-this-secret-key
    access-token-expiration: 900000
    refresh-token-expiration: 604800000